### ISSUE TITLE
How to call babylongrid:resize after assets are loaded

### ISSUE THREAD

**Issue by Master-Antonio** [turboMaCk/Babylon-Grid#7] opened 2016-01-12 21:28 UTC
Example : I set in this way.
```
(function($){

				$('#grigliarticoli').babylongrid({
					scheme: [
						{
							minWidth: 960,
							columns: 3
						},
						{
							minWidth: 500,
							columns: 2
						},
						{
							minWidth: 0,
							columns: 1
						}
					],
					afterRender: function() {
						console.log('Tutto Ok');
					}
				});
}(jQuery));
```

When zoom work , when zoom out (from 500 to 960 , from 0 to 500 , from 0 to 960 ) dont work, remains with the actual grid.

**Comment by turboMaCk** [comment] 2016-01-16 22:41
What you mean by `zoom`? I don't get it. Did it meant "resizing browser window??" I just tested it and it works for me with demo (included in this repository).

Can you please try to git clone this repo and open index.html? https://github.com/turboMaCk/Babylon-Grid/tree/master/demo

**Comment by turboMaCk** [comment] 2016-01-17 09:43
I just added gh-pages with demo: https://turbomack.github.io/Babylon-Grid/

**Comment by Master-Antonio** [comment] 2016-01-17 11:30
I mean when resizing the browser windows.
I think because there are images and video for this doesn't resize.
I did the gif.  https://i.gyazo.com/a21eb334cf27d483decc508b47a268a4.gif

**Comment by turboMaCk** [comment] 2016-01-17 11:50
Ok, now it's clean.

This is exactly about same issue: https://github.com/turboMaCk/Babylon-Grid/issues/1

The problem is that you re triggering that event before images/video is loaded, not after.
Try this:

```js
(function($){
  // set container
  var $grid = $('#babylongrid');

   // resize function – call this everytime you have to recalc
   function resizeGrid() {
      $grid.trigger('babylongrid:resize');
  }

   // init pligin
  $grid.babylongrid();

  // redraw after assets are loaded
  $grid.load(resize);
}(jQuery));

source: http://api.jquery.com/load-event/

For debugging you can call $('{selector}').trigger('babylongrid:resize') from [console](https://developers.google.com/web/tools/chrome-devtools/debug/console/console-ui) to see what it does.

**Comment by Master-Antonio** [comment] 2016-01-17 11:53
Uncaught ReferenceError: resize is not defined

**Comment by turboMaCk** [comment] 2016-01-17 11:54
^^ see pls pls... > use `resizeGrid` instead, sorry my typo.

**Comment by Master-Antonio** [comment] 2016-01-17 11:58
```
<script>
(function($){
  // set container
  var $grid = $('#grigliarticoli');

   // resize function – call this everytime you have to recalc
   function resizeGrid() {
      $grid.trigger('babylongrid:resizeGrid');
  }

   // init pligin
  $grid.babylongrid();

  // redraw after assets are loaded
  $grid.load(resizeGrid);
}(jQuery));
</script>
```

Now i call $('#grigliarticoli}').trigger('babylongrid:resizeGrid') in afterRender: function() {
						
						
					}

**Comment by turboMaCk** [comment] 2016-01-17 12:01
That does not make sense. Then you will fail in infinite recursion!triggering  `'babylongrid:resizeGrid'` force new render, after this happens `afterRender` is called.

**Comment by Master-Antonio** [comment] 2016-01-17 12:01
Yes. i saw, and where call $('#grigliarticoli').trigger('babylongrid:resizeGrid'); ?

**Comment by turboMaCk** [comment] 2016-01-17 12:06
as you can see I have variable `var $grid` in my code... just replace that line with your own element like:

```js
var $grid = $('#grigliarticoli');
```

another important line is
```js
$grid.babylongrid();
```

which initialize plugin on that element => you can add your custom options in here. To make it kind of nice but not way too complex lets said you ended with somethink like:

```js
(function($){
  // set container
  var $grid = $('#grigliarticoli');
  // set options
  var options = {
    scheme: [
          {
            minWidth: 960,
            columns: 3
          },
          {
            minWidth: 600,
            columns: 2
          },
          {
            minWidth: 0,
            columns: 1
          }
        ]
      });
  };

  // resize function – call this everytime you have to recalc
  function resizeGrid() {
    $grid.trigger('babylongrid:resize');
  }

  // init plugin with options
  $grid.babylongrid(options);

  // redraw after assets are loaded
  $grid.load(resizeGrid);
}(jQuery));
```

that's all

**Comment by turboMaCk** [comment] 2016-01-17 12:10
BTW as you can see that trigger is called in `resizeGrid` function;) :rocket: Copy->Paste and you're done.

**Comment by Master-Antonio** [comment] 2016-01-17 12:11
Yes , before i did in this way in fact.
But dont work.
https://i.gyazo.com/b8b09b28207bb98cf98d986d7dbaf911.gif

**Comment by turboMaCk** [comment] 2016-01-17 12:17
Gif is not much helpful. Try to post jsbin/jsfiddle or something like that.

**Comment by Master-Antonio** [comment] 2016-01-17 12:17
```
<script>
(function($){
  // set container
  var $grid = $('#grigliarticoli');
  // set options
  var options = {
    scheme: [
						{
							minWidth: 960,
							columns: 3
						},
						{
							minWidth: 500,
							columns: 2
						},
						{
							minWidth: 0,
							columns: 1
						}
					]
      };
  

  // resize function – call this everytime you have to recalc
  function resizeGrid() {
    $grid.trigger('babylongrid:resizeGrid');
  }

  // init plugin with options
  $grid.babylongrid(options);

  // redraw after assets are loaded
  $grid.load(resizeGrid);
}(jQuery));
</script>
```

Now dont give errors. But dont work.
https://i.gyazo.com/13054f3857827efa7fb047e40b99e4ee.png

**Comment by turboMaCk** [comment] 2016-01-17 12:18
Still not much useful. I need full code.. html, css, js.

http://jsbin.com/?html,css,js,output

**Comment by Master-Antonio** [comment] 2016-01-17 12:24
I use file in PHP, and my site is very BIG.  I can not copy all.
Are 40-50 files ....
Could be that i use Bootstrap?
Or because i use a embed.js.
Could be also because i use Ajax !

1) https://i.gyazo.com/69ce2d30a364ae1aaeed824496fc15d5.png
2) https://gyazo.com/b06374555d039dc02ecba5282e3ed637
3) https://i.gyazo.com/8a1bb87493829e7f255d8ffdf04156e2.png

**Comment by turboMaCk** [comment] 2016-01-17 12:36
If you cant copy your html render from php and include few files, than we are done here.
I can't debug gifs, sorry. I also probably spent more time on this than you.
Probably the issue is related with how you're embeding videos. There might be problem with iframes, but I haven't tested it. windows resize event is simply not triggered after video is loaded.

About zooming – this is browsers buisness. Behaviour of plugin is correct and depend on browser/os and so.

**Comment by Master-Antonio** [comment] 2016-01-17 12:37
Now i did. Thanks a lot.

**Comment by Master-Antonio** [comment] 2016-01-17 12:43
Is my ajax call because if i remove $('#grigliarticoli').trigger('babylongrid:load'); .
Dont work nothing.
https://i.gyazo.com/e617288421f66f70495f22b11ddbd46f.png

**Comment by Master-Antonio** [comment] 2016-01-17 12:46
Now i create a pen on Codepen.

**Comment by Master-Antonio** [comment] 2016-01-17 12:55
I created same problem here.
http://codepen.io/Master-Antonio/pen/JGrwWG/

**Comment by Master-Antonio** [comment] 2016-01-17 14:01
http://codepen.io/Master-Antonio/pen/JGrwWG/

**Comment by turboMaCk** [comment] 2016-01-17 14:07
THX this will help. I'll try to debug that issue. I'll let you know.

**Comment by Master-Antonio** [comment] 2016-01-17 14:12
Is not the embed.js and i add that is not the ajax.
Because now i tried with static html without embed and there is the same problem.

**Comment by turboMaCk** [comment] 2016-01-17 15:12
Ok so:

* You do not understand your actual problem
* You did not copy paste my code correctly
* You do not reporting issue on right place at all

The problem is, that embedJS (Why you didn't say that you are using it before?) do some async stuff but has no ability to pass callback or do not return promise. I made issue for that already: https://github.com/ritz078/embed.js/issues/111

Next problem is that you do not understand what's going on.

Babylon grid cashing dom to increase performance. Because of this you at least need to use [another api metod](https://github.com/turboMaCk/Babylon-Grid#ajax-support) to deal with this stuff but....
Because EmbedJS's api do not have support for callback you can't do it at all.

What you want (logically):
* init embed
* then init grid

Both things are async. You can not run babylon grid first because embed mutate dom, you need to init grid after embeding happens to cache DOM correctly.

This is kind of work hacky implementation, but I do not recommend you to use it in production (Basically this will break on slow internet connection):

https://github.com/turboMaCk/Babylon-Grid/commit/7443d2604d1b8b66e1a53d368216e761f0169e8c

That's it.

If embed.js team implments callback/promise, than you can basically init babylon grid right after embeding finish.

**Comment by Master-Antonio** [comment] 2016-01-17 15:14
Understand, but i tried also without the embed and there is the same problem.

**Comment by turboMaCk** [comment] 2016-01-17 15:14
**For a record:**

above is reaction on email by @Master-Antonio:

```
http://codepen.io/Master-Antonio/pen/JGrwWG/

And i conferm that isn't the embed. 
Because now i removed them in my site and i have the same problem.
```

**Comment by Master-Antonio** [comment] 2016-01-17 15:17
See . 
http://codepen.io/Master-Antonio/pen/obGmzE

**Comment by turboMaCk** [comment] 2016-01-17 15:18
There is no any problem. If you want to add content to grid use this: https://github.com/turboMaCk/Babylon-Grid#ajax-support

If you do not want to invalidate cache – did not mutate dom and want to reinit grid use: 
https://github.com/turboMaCk/Babylon-Grid#force-redraw-grid

Both things works. I waste too much time on this.

**Comment by Master-Antonio** [comment] 2016-01-17 15:22
In this way , dont force redraw grid?
```
(function($){
  // set container
  var $grid = $('#grigliacategorie');
  // set options
  var options = {
    scheme: [
						{
							minWidth: 960,
							columns: 4
						},
						{
							minWidth: 500,
							columns: 3
						},
						{
							minWidth: 0,
							columns: 1
						}
					]
      };
  

  // resize function – call this everytime you have to recalc
  function resizeGrid() {
    $grid.trigger('babylongrid:resizeGrid');
  }

  // init plugin with options
  $grid.babylongrid(options);

  // redraw after assets are loaded
  $grid.load(resizeGrid);
}(jQuery));
```

If is yes , i see problems ...
The 5 article is on the first article.
And the last article is on the second article.

**Comment by turboMaCk** [comment] 2016-01-17 15:25
Seriously? Are you trolling me? Try to read documentation, this discussion. What I see from that codepen is that you do not listen to me and you can't copy-paste.
<img width="473" alt="fuck" src="https://cloud.githubusercontent.com/assets/2130305/12378197/e7cca1d8-bd36-11e5-92c8-2c0dc06f0ae1.png">

**Comment by turboMaCk** [comment] 2016-01-17 15:25
Write that code one more time and without mistakes.

**Comment by Master-Antonio** [comment] 2016-01-17 15:26
https://i.gyazo.com/c2357c841cbdff151e3e5ad4af6d3acb.png

**Comment by turboMaCk** [comment] 2016-01-17 15:35
Were we go:
https://github.com/turboMaCk/Babylon-Grid/commit/f00c3ecf1f6061f557971ae1662c9ef5d8f92a37

^ this is demonstration that **IT'S WORKING**

closing issue, unsubscribing.

**Closed** 2016-01-17 15:35 UTC
Labels: duplicate, question

**Comment by turboMaCk** [comment] 2016-01-17 15:50
Sorry I really waste too much time on this. I have to do something constructive now. First read jQuery's documentation on `load` mehod (I posted link above). Than read babylon-grid's documentation and fix naming of events etc. Than it will work as expected. Or just copy my code and change class names etc. This is solution. There was never issue with babylongrid. You just need to use it properly (as documentation said).

**Comment by turboMaCk** [comment] 2016-01-17 17:41
@Master-Antonio See: https://github.com/ritz078/embed.js/issues/111#issuecomment-172356108

with embed.js you can add call of `$grid.trigger('babylongrid:resize')` in that hook like:

```js
//...
afterEmbedJSApply: function () {
  $grid.babylongrid();
}
//...
```

I'm not 100% sure how this is implemented on embed.js side but if this is called after new DOM is rendered that should work (if it's not waiting for DOM than maybe not. But you can still try listen to DOM's load event and try to force `babylongrid:resize` after DOM rendering is done.

**Comment by turboMaCk** [comment] 2016-01-17 19:28
@Master-Antonio I made better implementation with embed.js. This was a little bit harder but basically I just init embed on another element and when some article is ready script moves it inside grid and trigger `load`.

In this is implementation:
https://github.com/turboMaCk/Babylon-Grid/tree/example/ejs

**Comment by Master-Antonio** [comment] 2016-01-17 20:41
I discovered the problem.
For the Resizing the problem is the sidebar in the left.
For the last article that go in the top article i dont know, because now there isn't nothing, only your files and bootstrap, do same thing also without the sidebar.
![image](https://i.gyazo.com/af518b694136104346e234876908918e.png)

I create a reposity with all this, If you want to check it out..
https://github.com/Master-Antonio/Babylon-Problem

Excuse me if you are losing time.

**Comment by turboMaCk** [comment] 2016-01-17 22:29
that's css issue.

**Comment by Master-Antonio** [comment] 2016-01-17 22:33
In fact I deleted because I solved.

**Comment by Master-Antonio** [comment] 2016-01-17 22:41
In fact I deleted because I solved after 1 min and I did not want to waste your time.
I fixed all.
Remains only the problem of resizing for the sidebar.
Anyway there was no need of #ejs-grid ( the copy of the #grid ) . 
I solve normally using the #grid.

**Comment by turboMaCk** [comment] 2016-01-17 22:44
If you're using setTimeout then it will be always buggy. That logic was used for simulating something like observation pattern.

**Comment by Master-Antonio** [comment] 2016-01-17 22:45
Nono. With the ajax call.

**Comment by turboMaCk** [comment] 2016-01-17 22:48
Cool. Then it's the right way. Good luck.

**Comment by Master-Antonio** [comment] 2016-01-17 22:50
Thanks for all.
And for your time.
